apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    component: kibana
    role: kibana
spec:
  replicas: 1
  selector:
    component: kibana
    role: kibana
  template:
    metadata:
      labels:
        component: kibana
        role: kibana
    spec:
      containers:
      - name: kibana-dashboard
        image: coursierprive/docker-kibana:4.5.3
        env:
        - name: KIBANA_ES_URL
          value: "http://elasticsearch:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
